### ISSUE TITLE
Problem when installing ( compiling phase )

### ISSUE THREAD

**Issue by MajbriOussema** [io12/pwninit#106]
Hello,
I am always having this error when installing pwninit, is it from caused by the last update ? can you help me.
Thank you
**Compiling pwninit v3.0.1
error[E0277]: a value of type `std::ffi::OsString` cannot be built from an iterator over elements of type `&_`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pwninit-3.0.1/src/patch_bin.rs:112:10**
![Capture](https://user-images.githubusercontent.com/58023303/123414495-dd11fe80-d5ab-11eb-81a0-f7f25b8cd021.PNG)

**Comment by MRX-0** [comment]
same issue here, going crazy :)

**Comment by io12** [comment]
What version of Rust do you have installed and does updating to the latest stable Rust fix it?

**Comment by MajbriOussema** [comment]
v1.53.0.
I think this is the latest version.
![Capture2](https://user-images.githubusercontent.com/58023303/123483915-6bfc3680-d5ff-11eb-84a0-f3125a93190c.PNG)

**Comment by io12** [comment]
That is really confusing. I tried just now with v1.53.0 and it worked for me, and v1.53.0 added this feature https://github.com/rust-lang/rust/blob/master/RELEASES.md#libraries-1. Are you *sure* you're compiling with v1.53.0?

**Comment by Lambangaw** [comment]
reinstall your rust may be it can fix this problem

**Comment by io12** [comment]
@Lambangaw's suggestion to reinstall Rust is a good idea. I'm going to close this issue for inactivity ~~and because I have no idea what the problem is~~, but feel free to reopen it if you still have the issue. Worst case, I can change the way it does `OsString` concatenation.

**Comment by ret2src** [comment]
Quick fix that worked for me on Kali Linux: Install Rust using the official installer script instead of the version in the Kali repos (v1.48 vs. v1.53 at the time of writing):

1. Make sure to uninstall the repo version first:
`sudo apt remove --purge cargo && sudo apt autoremove`

2. Install using the script provided [here](https://www.rust-lang.org/tools/install):
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

3. Build pwninit:
`cargo install pwninit`

![image](https://user-images.githubusercontent.com/2010034/127138163-930b0671-8faa-492f-89e6-ae245e52170f.png)
